---
- name: Install UFW
  become: true
  apt:
    name: ufw
    state: latest

- name: Enable firewall
  ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: Allow SSH
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
